id: A2C482202
title: 'All-Pervading Auspiciousness: An Aspiration for the Spread of the Teachings
  of the Eight Great Chariots of the Practice Lineage'
type: translation
pechas:
- I3D5D0496
- IA49037A3
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:06:20.026424
  last_modified_at: 2023-01-04 12:06:20.026433
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  I3D5D0496/5DB3: '3019'
  IA49037A3/E737: '3019'
